// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iprpojebbueihznjpaxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwcnBvamViYnVlaWh6bmpwYXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwODM0MDYsImV4cCI6MjA4NDY1OTQwNn0.l5U7EDByo66j73m9EFhCM-9i1tvg-Qsc4dEb34kKxOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);