// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nidcadxnzczqfgpmucgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pZGNhZHhuemN6cWZncG11Y2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNjk0ODAsImV4cCI6MjA1Njc0NTQ4MH0.8WIa3GfxqhdJ47R82Jk1o86Jk-x91bang-icrFsYF-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);